services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL= jdbc:postgresql://db:5432/demo
      - DATABASE_USERNAME= truong
      - DATABASE_PASSWORD = 123  
    ports:
      - "8089:8089"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "truong"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "demo"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
  
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data: {}